# Series from patches.armbian/
	patches.armbian/clk-rockchip-rv1106.patch
	patches.armbian/hwrng-rockchip-rng-bsp.patch
	patches.armbian/iio-adc-rockchip-saradc-rv1106.patch
	patches.armbian/net-phy-rk630.patch
	patches.armbian/net-stmmac-rv1106.patch
	patches.armbian/nvmem-rockchip-otp-rv1106.patch
	patches.armbian/phy-rockchip-inno-usb2-rv1106.patch
	patches.armbian/pinctrl-rockchip-rv1106.patch
	patches.armbian/rtc-rockchip-rv1106.patch
	patches.armbian/soc-rockchip-npor-powergood.patch
	patches.armbian/thermal-rockchip-rv1106.patch
